import {
  FaBookOpen,
  FaCalendarCheck,
  FaChartLine,
  FaCog,
  FaCreditCard,
  FaEnvelope,
  FaImages,
  FaPenNib,
  FaServicestack,
  FaStar,
  FaUsers,
  FaUserShield,
} from 'react-icons/fa';

export const adminNav = [
  { label: 'Dashboard', path: '/admin', icon: FaChartLine },
  { label: 'Bookings', path: '/admin/bookings', icon: FaCalendarCheck },
  { label: 'Services', path: '/admin/services', icon: FaServicestack },
  { label: 'Contacts', path: '/admin/contacts', icon: FaEnvelope },
  { label: 'Blogs', path: '/admin/blogs', icon: FaPenNib },
  { label: 'Travel Guides', path: '/admin/guides', icon: FaBookOpen },
  { label: 'Gallery', path: '/admin/gallery', icon: FaImages },
  { label: 'Reviews', path: '/admin/reviews', icon: FaStar },
  { label: 'Customers', path: '/admin/customers', icon: FaUsers },
  { label: 'Payments', path: '/admin/payments', icon: FaCreditCard },
  { label: 'Staff', path: '/admin/staff', icon: FaUserShield },
  { label: 'Settings', path: '/admin/settings', icon: FaCog },
];

export const resourceConfig = {
  bookings: {
    title: 'Booking Management',
    description: 'Handle hotel, ticket, photography, video, and trip booking inquiries.',
    primaryField: 'customerName',
    statusField: 'status',
    columns: ['customerName', 'serviceId', 'destination', 'eventDate', 'guests', 'budget', 'status', 'paymentStatus'],
    fields: [
      { name: 'customerName', label: 'Customer Name', type: 'text', required: true },
      { name: 'email', label: 'Email', type: 'email', required: true },
      { name: 'phone', label: 'Phone', type: 'text', required: true },
      { name: 'serviceId', label: 'Service Type', type: 'select', options: ['hotel-bookings', 'ticket-bookings', 'photography', 'short-videos', 'trip-bookings'], required: true },
      { name: 'destination', label: 'Destination / Location', type: 'text', required: true },
      { name: 'eventDate', label: 'Date', type: 'date', required: true },
      { name: 'guests', label: 'Guests', type: 'number', required: true },
      { name: 'budget', label: 'Budget', type: 'text', required: true },
      { name: 'status', label: 'Status', type: 'select', options: ['pending', 'contacted', 'confirmed', 'in-progress', 'completed', 'cancelled'] },
      { name: 'paymentStatus', label: 'Payment Status', type: 'select', options: ['unpaid', 'partial', 'paid', 'refunded'] },
      { name: 'travelStyle', label: 'Travel Style', type: 'text' },
      { name: 'message', label: 'Special Requirements', type: 'textarea' },
      { name: 'quotedAmount', label: 'Quoted Amount', type: 'number' },
    ],
  },
  services: {
    title: 'Service Management',
    description: 'Add, edit, disable, and price Free2Spread services.',
    primaryField: 'title',
    statusField: 'availability',
    columns: ['title', 'category', 'price', 'priceRange', 'availability', 'active'],
    fields: [
      { name: 'title', label: 'Service Name', type: 'text', required: true },
      { name: 'category', label: 'Category', type: 'select', options: ['travel', 'creative', 'photography'], required: true },
      { name: 'description', label: 'Description', type: 'textarea', required: true },
      { name: 'price', label: 'Starting Price', type: 'number', required: true },
      { name: 'priceRange', label: 'Price Range', type: 'text' },
      { name: 'duration', label: 'Duration', type: 'text' },
      { name: 'imageUrl', label: 'Image URL', type: 'text' },
      { name: 'availability', label: 'Availability', type: 'select', options: ['available', 'limited', 'unavailable'] },
      { name: 'active', label: 'Active', type: 'checkbox' },
    ],
  },
  contacts: {
    title: 'Contact Inquiries',
    description: 'View, filter, mark, and follow up contact form messages.',
    primaryField: 'name',
    statusField: 'status',
    columns: ['name', 'email', 'subject', 'status', 'replyStatus', 'createdAt'],
    fields: [
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'email', label: 'Email', type: 'email', required: true },
      { name: 'subject', label: 'Subject', type: 'text', required: true },
      { name: 'message', label: 'Message', type: 'textarea', required: true },
      { name: 'status', label: 'Status', type: 'select', options: ['unread', 'read', 'replied', 'archived'] },
      { name: 'replyStatus', label: 'Reply Status', type: 'select', options: ['pending', 'replied'] },
      { name: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
  blogs: {
    title: 'Blog Management',
    description: 'Create travel articles, SEO metadata, and publish/draft blog content.',
    primaryField: 'title',
    statusField: 'status',
    columns: ['title', 'category', 'status', 'seoTitle', 'updatedAt'],
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'slug', label: 'SEO URL Slug', type: 'text', required: true },
      { name: 'category', label: 'Category', type: 'select', options: ['Travel Articles', 'Destination Guides', 'Photography Tips', 'Travel Hacks', 'Visa Information', 'Trending Destinations'] },
      { name: 'excerpt', label: 'Excerpt', type: 'textarea' },
      { name: 'content', label: 'Content', type: 'textarea', required: true },
      { name: 'featuredImage', label: 'Featured Image URL', type: 'text' },
      { name: 'seoTitle', label: 'SEO Title', type: 'text' },
      { name: 'metaDescription', label: 'Meta Description', type: 'textarea' },
      { name: 'status', label: 'Status', type: 'select', options: ['Draft', 'Published'] },
    ],
  },
  guides: {
    title: 'Travel Guide Management',
    description: 'Manage destination guides, travel tips, visa guides, packing lists, and safety content.',
    primaryField: 'title',
    statusField: 'status',
    columns: ['title', 'type', 'destination', 'status', 'updatedAt'],
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'slug', label: 'Slug', type: 'text', required: true },
      { name: 'type', label: 'Guide Type', type: 'select', options: ['Destination Guide', 'Travel Tip', 'Visa Guide', 'Packing Checklist', 'Budget Planning', 'Safety Tip'] },
      { name: 'destination', label: 'Destination', type: 'text' },
      { name: 'summary', label: 'Summary', type: 'textarea' },
      { name: 'content', label: 'Content', type: 'textarea', required: true },
      { name: 'featuredImage', label: 'Featured Image URL', type: 'text' },
      { name: 'status', label: 'Status', type: 'select', options: ['Draft', 'Published'] },
    ],
  },
  gallery: {
    title: 'Gallery Management',
    description: 'Manage photos, videos, albums, categories, and featured media.',
    primaryField: 'title',
    statusField: 'type',
    columns: ['title', 'type', 'category', 'album', 'featured', 'active'],
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'description', label: 'Description', type: 'textarea' },
      { name: 'type', label: 'Type', type: 'select', options: ['Photo', 'Video'] },
      { name: 'category', label: 'Category', type: 'text' },
      { name: 'album', label: 'Album', type: 'text' },
      { name: 'url', label: 'Media URL', type: 'text', required: true },
      { name: 'thumbnailUrl', label: 'Thumbnail URL', type: 'text' },
      { name: 'featured', label: 'Featured', type: 'checkbox' },
      { name: 'active', label: 'Active', type: 'checkbox' },
    ],
  },
  reviews: {
    title: 'Reviews Management',
    description: 'Approve, reject, edit, feature, and add manual customer reviews.',
    primaryField: 'name',
    statusField: 'status',
    columns: ['name', 'service', 'rating', 'status', 'featured', 'createdAt'],
    fields: [
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'email', label: 'Email', type: 'email', required: true },
      { name: 'location', label: 'Location', type: 'text' },
      { name: 'service', label: 'Service', type: 'text', required: true },
      { name: 'rating', label: 'Rating', type: 'number', required: true },
      { name: 'message', label: 'Review', type: 'textarea', required: true },
      { name: 'status', label: 'Status', type: 'select', options: ['pending', 'approved', 'rejected'] },
      { name: 'featured', label: 'Featured', type: 'checkbox' },
    ],
  },
  customers: {
    title: 'Customer Management',
    description: 'View customers, contact details, booking history notes, tags, and follow-up context.',
    primaryField: 'name',
    columns: ['name', 'email', 'phone', 'city', 'updatedAt'],
    fields: [
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'email', label: 'Email', type: 'email' },
      { name: 'phone', label: 'Phone', type: 'text' },
      { name: 'city', label: 'City', type: 'text' },
      { name: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
  payments: {
    title: 'Payment Management',
    description: 'Track paid, unpaid, partial, refunded payments and invoice references.',
    primaryField: 'customerName',
    statusField: 'status',
    columns: ['customerName', 'amount', 'method', 'status', 'invoiceNumber', 'paidAt'],
    fields: [
      { name: 'customerName', label: 'Customer Name', type: 'text' },
      { name: 'amount', label: 'Amount', type: 'number', required: true },
      { name: 'method', label: 'Method', type: 'select', options: ['Cash', 'UPI', 'Card', 'Bank Transfer', 'Other'] },
      { name: 'status', label: 'Status', type: 'select', options: ['Unpaid', 'Partial', 'Paid', 'Refunded'] },
      { name: 'transactionId', label: 'Transaction ID', type: 'text' },
      { name: 'invoiceNumber', label: 'Invoice Number', type: 'text' },
      { name: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
  staff: {
    title: 'Staff Management',
    description: 'Add staff, assign bookings, and manage role permissions.',
    primaryField: 'name',
    statusField: 'role',
    columns: ['name', 'email', 'phone', 'role', 'active'],
    fields: [
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'email', label: 'Email', type: 'email', required: true },
      { name: 'phone', label: 'Phone', type: 'text' },
      { name: 'role', label: 'Role', type: 'select', options: ['Admin', 'Staff'] },
      { name: 'active', label: 'Active', type: 'checkbox' },
      { name: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
  settings: {
    title: 'Website Settings',
    description: 'Update hero text, about content, contact details, FAQs, footer, privacy, and terms.',
    primaryField: 'key',
    columns: ['key', 'updatedAt'],
    fields: [
      { name: 'key', label: 'Settings Key', type: 'text', required: true },
      { name: 'aboutContent', label: 'About Page Content', type: 'textarea' },
      { name: 'footerContent', label: 'Footer Content', type: 'textarea' },
      { name: 'privacyPolicy', label: 'Privacy Policy', type: 'textarea' },
      { name: 'terms', label: 'Terms & Conditions', type: 'textarea' },
    ],
  },
};
